# Generated by Django 3.1.2 on 2020-10-27 20:36

import datetime
from django.db import migrations, models
import places.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=50, verbose_name='Event Name')),
                ('location_text', models.CharField(max_length=100, verbose_name='Location')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default='14:30', help_text='Enter in 24 hour format (eg - 2:45 or 16:45)')),
                ('category_text', models.CharField(choices=[('1', 'Food'), ('2', 'Career'), ('3', 'Physical Activity'), ('4', 'Civic Engagement'), ('5', 'Other')], default='1', max_length=50, verbose_name='Category')),
                ('description_text', models.CharField(max_length=200, verbose_name='Description')),
                ('location', places.fields.PlacesField(max_length=255)),
            ],
        ),
    ]
