# Generated by Django 3.1 on 2020-10-20 05:17

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=50)),
                ('location_text', models.CharField(max_length=100)),
                ('time_text', models.CharField(max_length=20)),
                ('category_text', models.CharField(max_length=50)),
                ('description_text', models.CharField(max_length=200)),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
    ]
