# Generated by Django 3.1.1 on 2020-10-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(default='', max_length=50)),
                ('location_text', models.CharField(max_length=100)),
                ('time_text', models.CharField(max_length=20)),
                ('category_text', models.CharField(max_length=50)),
                ('description_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='PostEvent',
        ),
    ]
