# Generated by Django 3.1.1 on 2020-10-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category_text',
            field=models.CharField(choices=[('1', 'FOOD'), ('2', 'CAREER'), ('3', 'ACTIVE'), ('4', 'CIVIC ENGAGEMENT'), ('5', 'OTHER')], default='1', max_length=50),
        ),
    ]
