# Generated by Django 3.1.2 on 2020-10-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostEvent',
            new_name='Event',
        ),
    ]
