# Generated by Django 3.1.1 on 2020-10-21 19:12

import datetime
from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201021_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time_text',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='14:30'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category_text',
            field=models.CharField(choices=[('1', 'FOOD'), ('2', 'CAREER'), ('3', 'PHYSICAL ACTIVITY'), ('4', 'CIVIC ENGAGEMENT'), ('5', 'OTHER')], default='1', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_text',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_text',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_text',
            field=models.CharField(max_length=50, verbose_name='Event Name'),
        ),
    ]
