# Generated by Django 3.1.1 on 2020-10-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201018_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title_text',
            field=models.CharField(max_length=50),
        ),
    ]
