# Generated by Django 3.1.2 on 2020-11-22 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20201111_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rsvps',
            field=models.ManyToManyField(related_name='rsvps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, to='events.Category'),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
