# Generated by Django 3.1.1 on 2020-11-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
