# Generated by Django 3.1.1 on 2020-10-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201021_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category_text',
            field=models.CharField(choices=[('1', 'Food'), ('2', 'Career'), ('3', 'Physical Activity'), ('4', 'Civic Engagement'), ('5', 'Other')], default='1', max_length=50, verbose_name='Category'),
        ),
    ]
