# Generated by Django 3.1.1 on 2020-11-03 16:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Food'), ('2', 'Career'), ('3', 'Physical Activity'), ('4', 'Civic Engagement'), ('5', 'Other')], default='1', max_length=50, verbose_name='Category'),
        ),
    ]
