# Generated by Django 3.1.1 on 2020-11-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201103_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.CharField(choices=[('1', 'Food'), ('2', 'Career'), ('3', 'Physical Activity'), ('4', 'Civic Engagement'), ('5', 'Other')], default='1', max_length=50, verbose_name='Category'),
        ),
    ]
