# Generated by Django 3.1.1 on 2020-11-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20201103_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='category_text',
            field=models.CharField(default='Uncategorized', max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_text',
            field=models.CharField(max_length=255, verbose_name='Event Name'),
        ),
    ]
