# Generated by Django 3.1.1 on 2020-11-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
