# Generated by Django 3.1.1 on 2020-11-05 18:03

from django.db import migrations
from django.conf import settings

def make_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model('events', 'Profile')
    profiles = [Profile(user=user) for user in User.objects.filter(profile=None)]
    Profile.objects.bulk_create(profiles)

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.RunPython(make_profiles),
    ]
