# Generated by Django 3.1.1 on 2020-11-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20201105_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='categories',
        ),
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(to='events.Category'),
        ),
    ]
